version: '3' # composeファイルのバージョン
services:
  comic-go: # サービス名
    container_name: app
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: Dockerfile
    volumes: # マウントディレクトリ
      - .:/go/src/app
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - .go_env
    ports:
      - 29000:8080
